/* ========================================================================
   CRYSTAL TECH — UI STRINGS DICTIONARY (single source of truth, en/fa)
   ======================================================================== */

window.CTS_STRINGS = {
  en: {
    nav: {
      home: "Home",
      services: "Services",
      about: "About",
      work: "Work",
      blog: "Blog",
      contact: "Contact",
      signin: "Sign in",
      signup: "Sign up",
      startProject: "Start a project"
    },
    mega: {
      flagship: "Flagship",
      dept1Name: "Web Design & Development",
      dept1Desc: "Websites, apps & platforms built to grow with you.",
      dept2Name: "Infrastructure & Hosting",
      dept2Desc: "Hosting, domains & the foundations that keep you online.",
      dept3Name: "Cloud & IT Consulting",
      dept3Desc: "Strategy, cloud advisory & security guidance.",
      viewAll: "View all services"
    },
    footer: {
      tagline: "Where creativity meets technology.",
      servicesHeading: "Services",
      companyHeading: "Studio",
      reachHeading: "Reach us",
      email: "hello@crystaltechservices.com",
      hq: "Herat, Afghanistan",
      global: "Working worldwide",
      copyright: "© 2025 CRYSTAL TECH SERVICES",
      taglineCaps: "WHERE CREATIVITY MEETS TECHNOLOGY"
    },
    common: {
      seeWork: "See our work",
      ourServices: "Our services",
      readMore: "Read more",
      learnMore: "Learn more",
      getStarted: "Get started",
      viewService: "View department",
      backToBlog: "Back to blog",
      allDepartments: "All departments",
      exploreDept: "Explore department",
      whatWeOffer: "What we offer",
      relatedPosts: "Related posts",
      search: "Search",
      searchPlaceholder: "Search articles…",
      categories: { all: "All", technology: "Technology", business: "Business", tips: "Tips", company: "Company News" },
      minRead: "min read",
      by: "by",
      trustedBy: "TRUSTED BY ORGANIZATIONS WORLDWIDE",
      ourTeam: "Our Team",
      otherDepartments: "Other departments",
      dashboardLink: "Dashboard",
      logout: "Log out",
      writeArticle: "Write an article",
      signInToWrite: "Sign in to write"
    },
    home: {
      eyebrow: "Where creativity meets technology",
      headlinePre: "Design that",
      headlineAccent: "performs.",
      headlinePost: "Technology that lasts.",
      lead: "From creative branding to full-scale digital transformation, we help businesses, NGOs, and startups build secure, scalable digital products — beautifully.",
      chip1: "crafted since 2020",
      chip2: "Herat → worldwide",
      execEyebrow: "01 — Who we are",
      execHeading: "Simplifying complexity",
      execBody: "Crystal Tech Services helps organizations move from idea to impact. We combine the discipline of engineering with the sensibility of design, delivering digital products and infrastructure that are dependable, secure, and built to grow. What began in 2020 as a creative design studio has grown into a technology solutions company serving businesses, NGOs, startups, and public organizations. Today our work spans web and software development, cloud and IT consulting, and cybersecurity advisory — always guided by a single principle: simplifying complexity for the people who rely on it.",
      hq: "Headquartered in Herat, Afghanistan. Working with clients worldwide.",
      statement: "We build technology businesses can trust — and that people can actually use.",
      deptEyebrow: "02 — What we do",
      deptHeading: "Three departments, one standard",
      deptSub: "Web design leads. Infrastructure keeps you running. Consulting keeps you moving forward.",
      statsEyebrow: "03 — By the numbers",
      testiEyebrow: "04 — Client voices",
      testiHeading: "What our clients say",
      ctaHeading: "Have a project in mind? Let's build something that performs.",
      ctaPrimary: "Start a project",
      ctaSecondary: "See our work"
    },
    servicesPage: {
      eyebrow: "Services",
      heading: "Three departments. One standard of craft.",
      lead: "From your first pixel to your last server log — we design, build, host, and advise on the systems that carry your organization forward.",
      servicesIn: "Services in this department"
    },
    about: {
      eyebrow: "About us",
      heading: "Design-led. Engineering-deep.",
      storyEyebrow: "Our story",
      storyHeading: "From studio to technology company",
      mvEyebrow: "Mission & Vision",
      missionTitle: "Mission",
      mission: "To simplify complexity for the organizations we serve — combining the discipline of engineering with the sensibility of design, so that every product and system we deliver is dependable, secure, and genuinely useful to the people who rely on it.",
      visionTitle: "Vision",
      vision: "To be the technology partner organizations trust for the full journey — from first impression to lasting infrastructure — proving that creativity and engineering, done right, are not a trade-off but a single standard.",
      valuesEyebrow: "What we stand for",
      valuesHeading: "The principles behind our work",
      whyEyebrow: "Why Crystal Tech",
      whyHeading: "A rare combination: design sense and engineering depth",
      statsEyebrow: "By the numbers",
      teamEyebrow: "The people",
      teamHeading: "Our Team"
    },
    work: {
      eyebrow: "Our work",
      heading: "Trusted by organizations across sectors",
      lead: "From NGOs to retail to logistics, we've helped organizations of every kind build a digital presence that performs.",
      clientsEyebrow: "Clients",
      testiEyebrow: "Testimonials"
    },
    contact: {
      eyebrow: "Contact",
      heading: "Let's talk",
      lead: "Tell us about your project — we'll get back to you within one business day.",
      formName: "Name",
      formEmail: "Email",
      formSubject: "Subject",
      formMessage: "Message",
      formSubmit: "Send message",
      formNamePh: "Your full name",
      formEmailPh: "name@company.com",
      formSubjectPh: "What's this about?",
      formMessagePh: "Tell us about your project",
      formSuccess: "Thanks — your message has been sent. We'll be in touch within one business day.",
      locationsHeading: "Locations",
      hqCity: "Herat, Afghanistan",
      hqSub: "Headquarters",
      ltCity: "Lithuania",
      ltSub: "Regional representative",
      jpCity: "Japan",
      jpSub: "Regional representative",
      emailLabel: "Email us",
      hoursLabel: "Working hours",
      hours: "Sat – Thu, 9:00 – 17:00 (UTC+4:30)"
    },
    blog: {
      eyebrow: "Blog",
      heading: "News, tips & insight",
      lead: "News, technical tips, and insight on technology and business — from the Crystal Tech team.",
      featured: "Featured",
      contributeCta: "Want to write for us?",
      contributeSub: "Sign in to submit an article for review."
    },
    article: {
      shareLabel: "Share this article"
    },
    auth: {
      signinHeading: "Welcome back",
      signinSub: "Sign in to your Crystal Tech account",
      signupHeading: "Create your account",
      signupSub: "Join the Crystal Tech community",
      nameLabel: "Full name",
      namePh: "Jane Doe",
      emailLabel: "Email",
      emailPh: "name@company.com",
      passLabel: "Password",
      passPh: "••••••••",
      confirmLabel: "Confirm password",
      rememberMe: "Remember me",
      forgotPass: "Forgot password?",
      signinBtn: "Sign in",
      signupBtn: "Create account",
      noAccount: "Don't have an account?",
      hasAccount: "Already have an account?",
      orDivider: "or"
    },
    contribute: {
      modalTitle: "Would you like to publish an article on our blog?",
      modalBody: "Share your knowledge with our community — approved articles go live on the Crystal Tech blog with full author credit.",
      yes: "Yes, let's go",
      notNow: "Not now",
      consentTitle: "Contributor agreement",
      consentBody: "Before continuing, please read and accept our contribution terms. Articles must be original, relevant to technology or business, and free of promotional spam. Crystal Tech reserves the right to edit for clarity and to approve or decline submissions.",
      consentCheck: "I agree to the contribution terms",
      continueBtn: "Continue",
      formTitle: "Write / submit article",
      fieldTitle: "Title",
      fieldTitlePh: "Give your article a clear, compelling title",
      fieldCategory: "Category",
      fieldCover: "Cover image",
      fieldCoverHint: "Drag & drop an image, or click to browse",
      fieldBody: "Article body",
      fieldBodyPh: "Write your article here…",
      submitBtn: "Submit for review",
      pendingTitle: "Your article is pending review.",
      pendingBody: "Thanks for your submission — our editorial team will review it shortly. You'll see the status update on your author dashboard.",
      dashboardBtn: "Go to author dashboard",
      dashHeading: "Author dashboard",
      dashSub: "Track the status of your submitted articles.",
      statusPending: "Pending",
      statusApproved: "Approved",
      statusRejected: "Rejected",
      newArticleBtn: "Write new article",
      navOverview: "Overview",
      navArticles: "My articles",
      navNew: "New article"
    }
  },

  fa: {
    nav: {
      home: "خانه",
      services: "خدمات",
      about: "درباره ما",
      work: "نمونه‌کارها",
      blog: "بلاگ",
      contact: "تماس",
      signin: "ورود",
      signup: "ثبت‌نام",
      startProject: "شروع یک پروژه"
    },
    mega: {
      flagship: "دپارتمان اصلی",
      dept1Name: "طراحی و توسعه‌ی وب",
      dept1Desc: "وب‌سایت‌ها، اپلیکیشن‌ها و پلتفرم‌هایی آماده‌ی رشد با شما.",
      dept2Name: "زیرساخت و میزبانی",
      dept2Desc: "میزبانی، دامنه و پایه‌هایی که شما را آنلاین نگه می‌دارند.",
      dept3Name: "مشاوره‌ی ابری و فناوری اطلاعات",
      dept3Desc: "راهبرد، مشاوره‌ی ابری و راهنمایی امنیتی.",
      viewAll: "مشاهده‌ی همه‌ی خدمات"
    },
    footer: {
      tagline: "جایی که خلاقیت با تکنولوژی گره می‌خورد.",
      servicesHeading: "خدمات",
      companyHeading: "استودیو",
      reachHeading: "ارتباط با ما",
      email: "hello@crystaltechservices.com",
      hq: "هرات، افغانستان",
      global: "همکاری در سراسر جهان",
      copyright: "© ۲۰۲۵ کریستال تک",
      taglineCaps: "جایی که خلاقیت با تکنولوژی گره می‌خورد"
    },
    common: {
      seeWork: "نمونه‌کارهای ما",
      ourServices: "خدمات ما",
      readMore: "بیشتر بخوانید",
      learnMore: "بیشتر بدانید",
      getStarted: "شروع کنید",
      viewService: "مشاهده‌ی دپارتمان",
      backToBlog: "بازگشت به بلاگ",
      allDepartments: "همه‌ی دپارتمان‌ها",
      exploreDept: "مشاهده‌ی دپارتمان",
      whatWeOffer: "آنچه ارائه می‌دهیم",
      relatedPosts: "مقاله‌های مرتبط",
      search: "جستجو",
      searchPlaceholder: "جستجوی مقاله‌ها…",
      categories: { all: "همه", technology: "تکنولوژی", business: "کسب‌وکار", tips: "نکته‌ها", company: "اخبار شرکت" },
      minRead: "دقیقه مطالعه",
      by: "نویسنده:",
      trustedBy: "مورد اعتماد سازمان‌ها در سراسر جهان",
      ourTeam: "تیم ما",
      otherDepartments: "سایر دپارتمان‌ها",
      dashboardLink: "پیشخوان",
      logout: "خروج",
      writeArticle: "نوشتن مقاله",
      signInToWrite: "برای نوشتن، وارد شوید"
    },
    home: {
      eyebrow: "جایی که خلاقیت با تکنولوژی گره می‌خورد",
      headlinePre: "طراحی‌ای که",
      headlineAccent: "نتیجه می‌دهد.",
      headlinePost: "تکنولوژی‌ای که ماندگار است.",
      lead: "از برندسازی خلاقانه تا تحول دیجیتال کامل، به کسب‌وکارها، سازمان‌های غیرانتفاعی و استارتاپ‌ها کمک می‌کنیم محصولات دیجیتال امن و مقیاس‌پذیر بسازند — با زیبایی.",
      chip1: "از سال ۲۰۲۰",
      chip2: "هرات → سراسر جهان",
      execEyebrow: "۰۱ — ما که هستیم",
      execHeading: "ساده‌کردن پیچیدگی",
      execBody: "کریستال تک به سازمان‌ها کمک می‌کند از ایده به نتیجه برسند. ما نظم مهندسی را با ذوق طراحی درهم می‌آمیزیم و محصولات و زیرساخت‌های دیجیتالی می‌سازیم که قابل‌اعتماد، امن و آماده‌ی رشد هستند. آنچه در سال ۲۰۲۰ به‌عنوان یک استودیوی طراحی خلاق آغاز شد، امروز به یک شرکت راهکارهای تکنولوژی تبدیل شده که به کسب‌وکارها، سازمان‌های غیرانتفاعی، استارتاپ‌ها و نهادهای عمومی خدمت می‌کند. امروز کار ما از توسعه‌ی وب و نرم‌افزار تا مشاوره‌ی ابری و امنیت سایبری را دربر می‌گیرد — و همیشه یک اصل راهنمای ماست: ساده‌کردن پیچیدگی برای کسانی که به آن تکیه می‌کنند.",
      hq: "دفتر مرکزی در هرات، افغانستان. همکاری با مشتریان در سراسر جهان.",
      statement: "تکنولوژی‌ای می‌سازیم که کسب‌وکارها به آن اعتماد کنند — و مردم واقعاً بتوانند از آن استفاده کنند.",
      deptEyebrow: "۰۲ — کارهای ما",
      deptHeading: "سه دپارتمان، یک استاندارد",
      deptSub: "طراحی وب پیشتاز است. زیرساخت شما را برخط نگه می‌دارد. مشاوره شما را به جلو می‌برد.",
      statsEyebrow: "۰۳ — آمار و ارقام",
      testiEyebrow: "۰۴ — نظر مشتریان",
      testiHeading: "مشتریان ما چه می‌گویند",
      ctaHeading: "پروژه‌ای در ذهن دارید؟ بیایید چیزی بسازیم که واقعاً نتیجه بدهد.",
      ctaPrimary: "شروع یک پروژه",
      ctaSecondary: "نمونه‌کارهای ما"
    },
    servicesPage: {
      eyebrow: "خدمات",
      heading: "سه دپارتمان. یک استاندارد از صنعتگری.",
      lead: "از نخستین پیکسل تا آخرین لاگ سرور — ما سیستم‌هایی را طراحی، ساخت، میزبانی و مشاوره می‌کنیم که سازمان شما را به جلو می‌برند.",
      servicesIn: "خدمات این دپارتمان"
    },
    about: {
      eyebrow: "درباره ما",
      heading: "خاستگاه طراحی‌محور. عمق مهندسی.",
      storyEyebrow: "داستان ما",
      storyHeading: "از استودیو تا شرکت تکنولوژی",
      mvEyebrow: "مأموریت و چشم‌انداز",
      missionTitle: "مأموریت",
      mission: "ساده‌کردن پیچیدگی برای سازمان‌هایی که به ما تکیه می‌کنند — با درهم‌آمیختن نظم مهندسی و ذوق طراحی، تا هر محصول و سیستمی که تحویل می‌دهیم قابل‌اعتماد، امن و واقعاً کارآمد باشد برای کسانی که به آن وابسته‌اند.",
      visionTitle: "چشم‌انداز",
      vision: "شریک تکنولوژیکی باشیم که سازمان‌ها در سراسر مسیر به آن اعتماد می‌کنند — از نخستین تأثیر تا زیرساخت ماندگار — و ثابت کنیم که خلاقیت و مهندسی، وقتی درست انجام شوند، نه یک دوراهی، بلکه یک استاندارد واحدند.",
      valuesEyebrow: "اصول ما",
      valuesHeading: "اصولی که پشت کار ماست",
      whyEyebrow: "چرا کریستال تک",
      whyHeading: "ترکیبی کمیاب: حس طراحی و عمق مهندسی",
      statsEyebrow: "آمار و ارقام",
      teamEyebrow: "افراد ما",
      teamHeading: "تیم ما"
    },
    work: {
      eyebrow: "نمونه‌کارها",
      heading: "مورد اعتماد سازمان‌ها در صنایع مختلف",
      lead: "از سازمان‌های غیرانتفاعی تا خرده‌فروشی و لجستیک، به سازمان‌های گوناگون کمک کرده‌ایم حضور دیجیتالی بسازند که واقعاً نتیجه می‌دهد.",
      clientsEyebrow: "مشتریان",
      testiEyebrow: "نظرات مشتریان"
    },
    contact: {
      eyebrow: "تماس",
      heading: "بیایید گفتگو کنیم",
      lead: "درباره‌ی پروژه‌تان به ما بگویید —ظرف یک روز کاری پاسخ می‌دهیم.",
      formName: "نام",
      formEmail: "ایمیل",
      formSubject: "موضوع",
      formMessage: "پیام",
      formSubmit: "ارسال پیام",
      formNamePh: "نام کامل شما",
      formEmailPh: "name@company.com",
      formSubjectPh: "موضوع پیام شما چیست؟",
      formMessagePh: "درباره‌ی پروژه‌تان بنویسید",
      formSuccess: "سپاسگزاریم — پیام شما ارسال شد. ظرف یک روز کاری با شما تماس می‌گیریم.",
      locationsHeading: "دفاتر ما",
      hqCity: "هرات، افغانستان",
      hqSub: "دفتر مرکزی",
      ltCity: "لیتوانی",
      ltSub: "نماینده‌ی منطقه‌ای",
      jpCity: "ژاپن",
      jpSub: "نماینده‌ی منطقه‌ای",
      emailLabel: "ایمیل به ما",
      hoursLabel: "ساعات کاری",
      hours: "شنبه تا پنجشنبه، ۹:۰۰ تا ۱۷:۰۰ (UTC+4:30)"
    },
    blog: {
      eyebrow: "بلاگ",
      heading: "اخبار، نکته‌ها و دیدگاه‌ها",
      lead: "اخبار، نکته‌های فنی و دیدگاه‌هایی درباره‌ی تکنولوژی و کسب‌وکار — از تیم کریستال تک.",
      featured: "ویژه",
      contributeCta: "می‌خواهید برای ما بنویسید؟",
      contributeSub: "برای ارسال مقاله جهت بررسی وارد شوید."
    },
    article: {
      shareLabel: "این مقاله را به اشتراک بگذارید"
    },
    auth: {
      signinHeading: "خوش برگشتید",
      signinSub: "وارد حساب کریستال تک خود شوید",
      signupHeading: "ساخت حساب کاربری",
      signupSub: "به جامعه‌ی کریستال تک بپیوندید",
      nameLabel: "نام کامل",
      namePh: "نام و نام خانوادگی",
      emailLabel: "ایمیل",
      emailPh: "name@company.com",
      passLabel: "رمز عبور",
      passPh: "••••••••",
      confirmLabel: "تکرار رمز عبور",
      rememberMe: "مرا به خاطر بسپار",
      forgotPass: "رمز عبور را فراموش کرده‌اید؟",
      signinBtn: "ورود",
      signupBtn: "ساخت حساب",
      noAccount: "حساب کاربری ندارید؟",
      hasAccount: "قبلاً حساب ساخته‌اید؟",
      orDivider: "یا"
    },
    contribute: {
      modalTitle: "مایل هستید مقاله‌ای در بلاگ ما منتشر کنید؟",
      modalBody: "دانش خود را با جامعه‌ی ما به اشتراک بگذارید — مقاله‌های تأییدشده با اعتبار کامل نویسنده در بلاگ کریستال تک منتشر می‌شوند.",
      yes: "بله",
      notNow: "فعلاً نه",
      consentTitle: "شرایط مشارکت",
      consentBody: "پیش از ادامه، لطفاً شرایط مشارکت را مطالعه و تأیید کنید. مقاله‌ها باید اصیل، مرتبط با تکنولوژی یا کسب‌وکار، و بدون تبلیغات نامرتبط باشند. کریستال تک حق ویرایش برای وضوح بیشتر و تأیید یا رد مقاله‌ها را برای خود محفوظ می‌دارد.",
      consentCheck: "شرایط را می‌پذیرم",
      continueBtn: "ادامه",
      formTitle: "نوشتن مقاله",
      fieldTitle: "عنوان",
      fieldTitlePh: "عنوانی روشن و جذاب برای مقاله‌تان بنویسید",
      fieldCategory: "دسته‌بندی",
      fieldCover: "تصویر شاخص",
      fieldCoverHint: "تصویر را بکشید و رها کنید یا کلیک کنید",
      fieldBody: "متن مقاله",
      fieldBodyPh: "مقاله‌ی خود را اینجا بنویسید…",
      submitBtn: "ارسال برای بررسی",
      pendingTitle: "مقاله‌ی شما در انتظار بررسی است.",
      pendingBody: "از ارسال شما سپاسگزاریم — تیم سردبیری ما به‌زودی آن را بررسی می‌کند. می‌توانید وضعیت را در پیشخوان نویسنده ببینید.",
      dashboardBtn: "رفتن به پیشخوان نویسنده",
      dashHeading: "پیشخوان نویسنده",
      dashSub: "وضعیت مقاله‌های ارسالی خود را پیگیری کنید.",
      statusPending: "در انتظار",
      statusApproved: "تأییدشده",
      statusRejected: "ردشده",
      newArticleBtn: "نوشتن مقاله‌ی جدید",
      navOverview: "نمای کلی",
      navArticles: "مقاله‌های من",
      navNew: "مقاله‌ی جدید"
    }
  }
};
